version: '2'
services:
    frontend:
        hostname: local-frontend
        working_dir: /usr/src/app
        build:
            context: ./
        ports:
            - "3000:3000"
        restart: always
        volumes:
          - "./:/usr/src/app"
